

#This is a dictionary that contains the common port numbers as the key and the service name and description as the value. 
#Used in the scan function to print the service name and description.
#Information from https://www.geeksforgeeks.org/50-common-ports-you-should-know/

port_to_service = {
7: ("Echo", "Echo service"),
20: ("FTP-data", "File Transfer Protocol data transfer"),
21: ("FTP", "File Transfer Protocol (FTP) control connection"),
22: ("SSH-SCP", "Secure Shell, secure logins, file transfers (scp, sftp), and port forwarding"),
23: ("Telnet", "Telnet protocol—unencrypted text communications"),
25: ("SMTP", "Simple Mail Transfer Protocol, used for email routing between mail servers"),
53: ("DNS",	"Domain Name System name resolver"),
69: ("TFTP", "Trivial File Transfer Protocol"),
80: ("HTTP", "Hypertext Transfer Protocol (HTTP) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP"),
88: ("Kerberos", "Network authentication system"),
102: ("Iso-tsap", "ISO Transport Service Access Point (TSAP) Class 0 protocol"),
110: ("POP3	TCP", "Post Office Protocol, version 3 (POP3)", "TCP"),
135: ("Microsoft", "Microsoft EPMAP (End Point Mapper), also known as DCE/RPC Locator service, used to remotely manage services including DHCP server, DNS server, and WINS. Also used by DCOM"),
137: ("NetBIOS-ns",	"NetBIOS Name Service, used for name registration and resolution"),
139: ("NetBIOS-ssn", "NetBIOS Session Service"),
143: ("IMAP4", "Internet Message Access Protocol (IMAP), management of electronic mail messages on a server"),
381: ("HP Openview", "HP data alarm manager"),
383: ("HP Openview", "HP data alarm manager"),
443: ("HTTP over SSL", "Hypertext Transfer Protocol Secure (HTTPS) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP."),
464: ("Kerberos", "Kerberos Change/Set password"),
465: ("SMTP over TLS/SSL,SSM", "Authenticated SMTP over TLS/SSL (SMTPS), URL Rendezvous Directory for SSM (Cisco protocol)"),
587: ("SMTP", "Email message submission"),
593: ("Microsoft DCOM", "HTTP RPC Ep Map, Remote procedure call over Hypertext Transfer Protocol, often used by Distributed Component Object Model services and Microsoft Exchange Server"),
636: ("LDAP over TLS/SSL", "Lightweight Directory Access Protocol over TLS/SSL"),
691: ("MS Exchange", "MS Exchange Routing"),
902: ("VMware Server", "VMware ESXi"),
989: ("FTP over SSL", "FTPS Protocol (data), FTP over TLS/SSL"),
990: ("FTP over SSL	", "FTPS Protocol (control), FTP over TLS/SSL"),
993: ("IMAP4 over SSL",	"Internet Message Access Protocol over TLS/SSL (IMAPS)"),
995: ("POP3 over SSL", "Post Office Protocol 3 over TLS/SSL"),
1025: ("Microsoft RPC", "Microsoft operating systems tend to allocate one or more unsuspected, publicly exposed services (probably DCOM, but who knows) among the first handful of ports immediately above the end of the service port range (1024+)."),
1194: ("OpenVPN", "OpenVPN"),
1337: ("WASTE",	"WASTE Encrypted File Sharing Program"),
1589: ("Cisco VQP", "Cisco VLAN Query Protocol (VQP)"),
1725: ("Steam",	"Valve Steam Client uses port 1725"),
2082: ("cPanel", "cPanel default"),
2083: ("radsec, cPanel", "Secure RADIUS Service (radsec), cPanel default SSL"),
2483: ("Oracle DB", "Oracle database listening for insecure client connections to the listener, replaces port 1521"),
2484: ("Oracle DB", "Oracle database listening for SSL client connections to the listener"),
2967: ("Symantec AV", "Symantec System Center agent (SSC-AGENT)"),
3074: ("XBOX Live",	"Xbox LIVE and Games for Windows Live"),
3306: ("MySQL",	"MySQL database system"),
3724: ("World of Warcraft",	"some Blizzard games, Unofficial Club Penguin Disney online game for kids"),
4664: ("Google Desktop", "Google Desktop Search"),
5432: ("PostgreSQL", "PostgreSQL database system"),
5900: ("RFB/VNC Server", "virtual Network Computing (VNC) Remote Frame Buffer RFB protocol"),
6665: ("IRC	TCP", "Internet Relay Chat "),
6669: ("IRC	TCP", "Internet Relay Chat"),
6881: ("BitTorrent", "BitTorrent is part of the full range of ports used most often"),
6999: ("BitTorrent", "BitTorrent is part of the full range of ports used most often"),
6970: ("Quicktime",	"QuickTime Streaming Server"),
8080: ("HTTP", "Hypertext Transfer Protocol (HTTP), Port that is generally used by web servers to make TCP connections if default port 80 is busy"),
8086: ("Kaspersky AV", "Kaspersky AV Control Center"),
8087: ("Kaspersky AV", "Kaspersky AV Control Center"),   
8222: ("VMware Server",  "VMware Server Management User Interface (insecure Web interface)."),
8443: ("HTTP over SSL", "HyperText Transfer Protocol Secure (HTTPS)  default port for Apache Tomcat"), 
9100: ("PDL", "Data Stream, used for printing to certain network printers[1"),
10000: ("BackupExec", "Webmin, Web-based Unix/Linux system administration tool (default port)"),
12345: ("NetBus", "NetBus remote administration tool (often Trojan horse)."),
27374: ("Sub7",	"Sub7 default"),
18006: ("Back Orifice", "Back Orifice 2000 remote administration tools"),
}        